services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
  
  backend:
    build:
      context: ./backend
    container_name: backend-service
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app          # Live sync code
      - /usr/src/app/node_modules       # Prevent local node_modules overwrite
    working_dir: /usr/src/app
    command: npm run dev                # Use nodemon for auto-restart

volumes:
  pgdata: