services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skillshare
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
    container_name: backend-service
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DB: skillshare
      PG_HOST: db
      PG_PORT: 5432
      BACKEND_PORT: 8080
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    command: npm run dev

   

volumes:
  pgdata:
